title: Mahesh's Tech Helpers
description: > # this means to ignore newlines until "baseurl:"
  Sharing is caring :) 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: MAHESH TANNEERU # add your name
author-img: mahesh.jpg # add your photo
about-author: I am an enthusiastic Software Engineer and a good Human being :)  # add description
social-twitter: mtanneeru17 # add your Twitter handle
social-facebook: mahesh.tanneeru # add your Facebook handle
social-github: tanneerumahesh # add your Github handle
social-linkedin: mahesh-tanneeru/ # add your Linkedin handle
social-email: tanneerumahesh@gmail.com

# Disqus
discus-identifier:  # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

google_ad_client:
site.google_tracking:

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
